/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

/**
 *
 * @author alisson 02
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnPrincipal = new javax.swing.JMenuBar();
        mnSistema = new javax.swing.JMenu();
        mnuSair = new javax.swing.JMenuItem();
        mnCadastro = new javax.swing.JMenu();
        mnuPessoaCadastro = new javax.swing.JMenuItem();
        mnuProdutoCadastro = new javax.swing.JMenuItem();
        mnRelatorio = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Vendas");
        setBackground(new java.awt.Color(102, 255, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frmPrincipal"); // NOI18N

        mnPrincipal.setMaximumSize(new java.awt.Dimension(1670, 32769));

        mnSistema.setText("Sistema");

        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnSistema.add(mnuSair);

        mnPrincipal.add(mnSistema);

        mnCadastro.setText("Cadastro");

        mnuPessoaCadastro.setText("Pessoa");
        mnuPessoaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPessoaCadastroActionPerformed(evt);
            }
        });
        mnCadastro.add(mnuPessoaCadastro);

        mnuProdutoCadastro.setText("Produto");
        mnCadastro.add(mnuProdutoCadastro);

        mnPrincipal.add(mnCadastro);

        mnRelatorio.setText("Relatórios");
        mnPrincipal.add(mnRelatorio);

        setJMenuBar(mnPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuPessoaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPessoaCadastroActionPerformed
        frmPessoaCadastro janela = new frmPessoaCadastro();
        add(janela);
        janela.setVisible(true);
    }//GEN-LAST:event_mnuPessoaCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenuBar mnPrincipal;
    private javax.swing.JMenu mnRelatorio;
    private javax.swing.JMenu mnSistema;
    private javax.swing.JMenuItem mnuPessoaCadastro;
    private javax.swing.JMenuItem mnuProdutoCadastro;
    private javax.swing.JMenuItem mnuSair;
    // End of variables declaration//GEN-END:variables
}
